from pathlib import Path
import json,sys
p=Path(sys.argv[1] if len(sys.argv)>1 else '/tmp/pc-lab.html')
s=p.read_text()
def rep(a,b,n):
 global s
 c=s.count(a)
 if c!=1: raise SystemExit(f'{n}: expected 1 match, got {c}')
 s=s.replace(a,b,1)
rep('<title>PC LAB v2.3.14 — 컴퓨터 조립 시뮬레이터</title><meta name="pc-lab-version" content="2.3.14"><meta name="pc-lab-build" content="2.3.14-96bd6394e936">','<title>PC LAB v2.3.15 — 컴퓨터 조립 시뮬레이터</title><meta name="pc-lab-version" content="2.3.15"><meta name="pc-lab-build" content="2.3.15-1ed8f3203523">','release identity')
rep("systemDisk:'m2'};","systemDisk:'m2',tutorialStep:0};",'tutorial ui state')
anchor="function btn(label,action,extra='',cls=''){return `<button class=\"btn ${cls}\" data-action=\"${action}\" ${extra}>${label}</button>`;}"
tutorial=r'''\nconst ONBOARDING_KEY='pc-lab:onboarding:v1:'+PS.hash(appScope);
const TUTORIAL_STEPS=[
 {icon:'cpu',kicker:'01 / 처음 시작',title:'PC LAB에 오신 것을 환영합니다',text:'이곳은 실제 컴퓨터를 망가뜨릴 걱정 없이 부품을 고르고, 조립하고, 원리를 살펴보는 가상 작업실입니다.',points:['실수해도 실제 기기에는 아무 변화가 없습니다.','모바일과 PC에서 같은 진행을 배울 수 있습니다.','모르는 부품이나 용어는 부품 사전에서 바로 확인할 수 있습니다.'],visual:'welcome'},
 {icon:'menu',kicker:'02 / 화면 둘러보기',title:'왼쪽 메뉴가 PC LAB의 지도입니다',text:'작업실에서 시작해 조립, 의뢰, 부품 사전, 활용 분석, 보관함, 기초 학습으로 이동할 수 있습니다.',points:['조립 작업대: 직접 PC를 만들고 분해하는 곳','의뢰 게시판: 증상을 보고 원인을 찾아 해결하는 곳','부품 사전·기초 학습: 처음 보는 규격과 용어를 익히는 곳'],visual:'menu'},
 {icon:'bench',kicker:'03 / 첫 작업 만들기',title:'처음에는 자유 조립으로 연습하세요',text:'새 작업에서 기기 종류와 시작 상태를 고른 뒤 작업대를 만들 수 있습니다. 처음이라면 데스크톱 PC와 빈 케이스가 가장 이해하기 쉽습니다.',points:['빈 케이스: 부품을 하나씩 장착하며 구조를 익힙니다.','완성 PC: 이미 조립된 상태에서 교체·분해를 연습합니다.','작업 중 막히면 작업대의 힌트 버튼을 사용할 수 있습니다.'],visual:'start'},
 {icon:'ram',kicker:'04 / 모바일 조립',title:'모바일은 부품 선택 → 슬롯 터치',text:'휴대폰에서는 긴 거리로 드래그하지 않아도 됩니다. 부품 목록에서 원하는 부품을 한 번 누르고, 본체의 호환되는 빈 슬롯을 한 번 누르면 장착됩니다.',points:['선택한 부품은 목록에서 강조되어 보입니다.','RAM은 RAM 슬롯 구역을 연 뒤 원하는 빈 슬롯을 터치합니다.','PC에서는 기존처럼 드래그 장착도 사용할 수 있습니다.'],visual:'tap'},
 {icon:'screw',kicker:'05 / 확대 작업과 분해',title:'분해는 고정장치를 먼저 확인하세요',text:'장착된 부품을 누르면 확대 작업으로 들어갈 수 있습니다. 나사·걸쇠·케이블이 남아 있으면 바로 빠지지 않습니다.',points:['가상 전원을 끄고 전원 코드가 분리된 상태인지 먼저 확인합니다.','확대 화면에서 나사와 걸쇠를 순서대로 풀어 상태를 확인합니다.','고정이 모두 풀린 부품은 분리 부품 놓는 곳으로 드래그해 꺼냅니다.'],visual:'service'},
 {icon:'save',kicker:'06 / 저장과 이동',title:'저장과 뒤로가기도 PC LAB 안에서 이어집니다',text:'진행을 남기고 싶다면 저장 버튼을 사용하세요. 자동 저장은 환경 설정에서 켤 수 있고, 모바일 브라우저 뒤로가기는 직전에 보던 PC LAB 화면으로 돌아갑니다.',points:['수동 저장 모드에서는 작업 후 저장 버튼을 눌러야 기록됩니다.','버전이 바뀌어도 버전 기록 창에서 변경 내용을 확인할 수 있습니다.','이 튜토리얼은 작업실 화면 아래의 “처음 튜토리얼 다시 보기”에서 언제든 다시 열 수 있습니다.'],visual:'finish'}
];
function tutorialSeen(){try{return localStorage.getItem(ONBOARDING_KEY)==='done';}catch{return false;}}
function markTutorialSeen(){try{localStorage.setItem(ONBOARDING_KEY,'done');}catch{}}
function tutorialVisual(kind){
 if(kind==='menu')return `<div class="tutorial-menu-grid">${[['bench','조립'],['jobs','의뢰'],['book','부품 사전'],['chart','활용 분석'],['box','보관함'],['learn','기초 학습']].map(([ic,t])=>`<span>${I(ic)}<b>${t}</b></span>`).join('')}</div>`;
 if(kind==='start')return `<div class="tutorial-flow"><span>${I('plus')}<b>새 작업</b></span><i>${I('arrow','small')}</i><span>${I('cpu')}<b>기기 선택</b></span><i>${I('arrow','small')}</i><span>${I('bench')}<b>작업대</b></span></div>`;
 if(kind==='tap')return `<div class="tutorial-flow tutorial-touch-flow"><span class="tutorial-part-chip">${I('ram')}<b>① 부품 터치</b></span><i>${I('arrow','small')}</i><span class="tutorial-slot-chip">${I('board')}<b>② 빈 슬롯 터치</b></span><i>${I('arrow','small')}</i><span>${I('check')}<b>장착</b></span></div>`;
 if(kind==='service')return `<div class="tutorial-flow"><span>${I('power')}<b>전원 확인</b></span><i>${I('arrow','small')}</i><span>${I('screw')}<b>고정 해제</b></span><i>${I('arrow','small')}</i><span>${I('box')}<b>분리함</b></span></div>`;
 if(kind==='finish')return `<div class="tutorial-flow"><span>${I('save')}<b>진행 저장</b></span><i>${I('arrow','small')}</i><span>${I('arrowleft')}<b>뒤로가기</b></span><i>${I('arrow','small')}</i><span>${I('home')}<b>이전 화면</b></span></div>`;
 return `<div class="tutorial-welcome-mark">${I('cpu')}<strong>PC LAB</strong><span>BUILD · LEARN · DISCOVER</span></div>`;
}
function tutorialDialog(step=0){const i=Math.max(0,Math.min(TUTORIAL_STEPS.length-1,Number(step)||0)),t=TUTORIAL_STEPS[i];ui.tutorialStep=i;const dots=TUTORIAL_STEPS.map((_,n)=>`<span class="${n===i?'active':n<i?'done':''}"></span>`).join('');const footer=i===TUTORIAL_STEPS.length-1?btn('처음 화면으로','tutorial-finish','','ghost')+btn(profile.current?'작업대로 가기':'첫 조립 시작','tutorial-start','','primary'):btn('건너뛰기','tutorial-skip','','ghost')+(i?btn('이전','tutorial-prev','','ghost'):'')+btn('다음','tutorial-next','','primary');modal('PC LAB 처음 튜토리얼',`<div class="first-tutorial"><div class="tutorial-progress"><div>${dots}</div><strong>${i+1} / ${TUTORIAL_STEPS.length}</strong></div><div class="tutorial-visual">${tutorialVisual(t.visual)}</div><div class="tutorial-copy"><div class="eyebrow">${S(t.kicker)}</div><h2>${S(t.title)}</h2><p>${S(t.text)}</p><ul>${t.points.map(x=>`<li>${S(x)}</li>`).join('')}</ul></div></div>`,footer,'wide tutorial-modal');}
function finishTutorial(start=false){markTutorialSeen();closeModal();if(start){if(profile.current)navigate('work');else{ui.newMode='free';newDialog();}}else toast('처음 튜토리얼을 완료했습니다. 작업실에서 언제든 다시 볼 수 있습니다.');}
'''
rep(anchor,anchor+tutorial,'tutorial functions')
rep('<div class="flex between wrap" style="margin-top:18px;gap:8px"><span class="label" style="font-size:.65rem">실제 기기를 제어하지 않는 가상 학습 환경입니다. 가격·성능·외형의 구현 범위를 확인하세요.</span><button class="text-btn" data-action="about">자료·구현 범위 ${I(\'info\',\'small\')}</button></div>`;','<div class="flex between wrap" style="margin-top:18px;gap:8px"><span class="label" style="font-size:.65rem">실제 기기를 제어하지 않는 가상 학습 환경입니다. 가격·성능·외형의 구현 범위를 확인하세요.</span><div class="flex gap-sm wrap"><button class="text-btn" data-action="tutorial">처음 튜토리얼 다시 보기 ${I(\'learn\',\'small\')}</button><button class="text-btn" data-action="about">자료·구현 범위 ${I(\'info\',\'small\')}</button></div></div>`;','tutorial replay button')
rep("case 'close-modal':if(ui.termOpen&&ui.termReturn?.product)restoreProductParent();else closeModal();break;","case 'close-modal':if(ui.modal==='PC LAB 처음 튜토리얼'){markTutorialSeen();closeModal();}else if(ui.termOpen&&ui.termReturn?.product)restoreProductParent();else closeModal();break;",'tutorial close')
rep("case 'resume':ui.headerMenu=false;closeModal();navigate('work');break;","case 'resume':ui.headerMenu=false;closeModal();navigate('work');break;\n case 'tutorial':tutorialDialog(0);break;\n case 'tutorial-next':tutorialDialog(ui.tutorialStep+1);break;\n case 'tutorial-prev':tutorialDialog(ui.tutorialStep-1);break;\n case 'tutorial-skip':markTutorialSeen();closeModal();toast('튜토리얼을 건너뛰었습니다. 작업실에서 언제든 다시 볼 수 있습니다.');break;\n case 'tutorial-finish':finishTutorial(false);break;\n case 'tutorial-start':finishTutorial(true);break;",'tutorial actions')
rep("['nav','home-workbench','new','settings','releases','product','detail-tab','term','detail-return','left-tab','right-tab','close-modal','recovery']","['nav','home-workbench','new','settings','releases','tutorial','tutorial-next','tutorial-prev','tutorial-start','product','detail-tab','term','detail-return','left-tab','right-tab','close-modal','recovery']",'tutorial click sounds')
rep("render();if(resumeLesson)setTimeout(()=>lessonDialog(resumeLesson),0);","render();if(resumeLesson)setTimeout(()=>lessonDialog(resumeLesson),0);else if(!tutorialSeen())setTimeout(()=>tutorialDialog(0),180);",'first run open')
css=r'''<style id="pc-lab-v2315-first-tutorial">
.tutorial-modal{max-width:780px!important}.first-tutorial{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:22px;align-items:stretch}.tutorial-progress{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:14px}.tutorial-progress>div{display:flex;gap:7px;flex:1}.tutorial-progress span{height:6px;flex:1;border-radius:999px;background:var(--line)}.tutorial-progress span.done,.tutorial-progress span.active{background:var(--accent)}.tutorial-progress strong{font-size:.72rem;color:var(--muted)}.tutorial-visual{min-height:250px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,color-mix(in srgb,var(--surface2) 90%,transparent),color-mix(in srgb,var(--accent) 5%,var(--surface)));display:flex;align-items:center;justify-content:center;padding:20px;overflow:hidden}.tutorial-copy{padding:10px 4px}.tutorial-copy h2{font-size:1.45rem;line-height:1.25;margin:8px 0 10px}.tutorial-copy>p{color:var(--muted);line-height:1.7;margin:0 0 16px}.tutorial-copy ul{display:grid;gap:9px;margin:0;padding:0;list-style:none}.tutorial-copy li{position:relative;padding-left:20px;color:var(--text);line-height:1.55;font-size:.9rem}.tutorial-copy li:before{content:'✓';position:absolute;left:0;color:var(--accent);font-weight:900}.tutorial-welcome-mark{text-align:center;display:grid;justify-items:center;gap:8px}.tutorial-welcome-mark svg{width:84px;height:84px;color:var(--accent);filter:drop-shadow(0 10px 24px color-mix(in srgb,var(--accent) 28%,transparent))}.tutorial-welcome-mark strong{font-family:var(--display);font-size:1.8rem;letter-spacing:.08em}.tutorial-welcome-mark span{font-size:.62rem;letter-spacing:.15em;color:var(--muted)}.tutorial-menu-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;width:100%}.tutorial-menu-grid span,.tutorial-flow span{display:flex;align-items:center;gap:9px;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--surface);min-width:0}.tutorial-menu-grid svg,.tutorial-flow svg{width:22px;height:22px;color:var(--accent);flex:none}.tutorial-menu-grid b,.tutorial-flow b{font-size:.8rem}.tutorial-flow{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap}.tutorial-flow>i{display:flex;color:var(--muted)}.tutorial-touch-flow .tutorial-part-chip,.tutorial-touch-flow .tutorial-slot-chip{box-shadow:0 0 0 2px color-mix(in srgb,var(--accent) 22%,transparent)}
@media(max-width:650px){.tutorial-modal{width:min(94vw,620px)!important}.first-tutorial{grid-template-columns:1fr;gap:14px}.tutorial-progress{grid-column:1}.tutorial-visual{min-height:180px;padding:14px;border-radius:17px}.tutorial-copy{padding:2px}.tutorial-copy h2{font-size:1.2rem}.tutorial-copy>p{font-size:.88rem;line-height:1.62}.tutorial-copy li{font-size:.82rem}.tutorial-menu-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.tutorial-menu-grid span{flex-direction:column;text-align:center;padding:9px 5px;gap:5px}.tutorial-menu-grid b{font-size:.68rem}.tutorial-flow{gap:5px}.tutorial-flow span{padding:9px 8px}.tutorial-flow b{font-size:.7rem}.tutorial-welcome-mark svg{width:62px;height:62px}}
</style>'''
if 'pc-lab-v2315-first-tutorial' not in s:s=s.replace('</head>',css+'</head>',1)
entry={'version':'2.3.15','date':'2026-09-15','timezone':'Asia/Seoul','channel':'stable-local','title':'첫 실행 튜토리얼 추가','changes':['PC LAB을 처음 실행하면 6단계 시작 튜토리얼이 한 번 자동으로 열리도록 추가','메뉴 구성, 첫 자유 조립 만들기, 모바일 부품 선택 → 슬롯 터치, 확대·분해, 저장과 브라우저 뒤로가기를 순서대로 안내','진행 표시와 그림형 안내, 이전·다음·건너뛰기·첫 조립 시작 버튼을 제공','완료하거나 건너뛴 뒤에는 자동으로 다시 뜨지 않으며 작업실 화면에서 언제든 다시 열 수 있도록 추가','만든이: 도구리 표기와 기존 모바일 조작 개선을 그대로 유지'],'scopeNote':'첫 실행 안내는 게임 조작을 배우기 위한 가상 튜토리얼이며 실제 컴퓨터 분해·조립 시에는 해당 기기의 제조사 안전 안내를 우선해야 합니다.'}
marker='</script><script>\n/* PC LAB content pack 0.1.0.'
j=json.dumps(entry,ensure_ascii=False,separators=(',',':'))
inject="</script><script>\nwindow.PCRelease.version='2.3.15';window.PCRelease.date='2026-09-15';window.PCRelease.buildId='2.3.15-1ed8f3203523';window.PCRelease.title="+json.dumps(entry['title'],ensure_ascii=False)+";window.PCRelease.changes="+json.dumps(entry['changes'],ensure_ascii=False)+";window.PCRelease.scopeNote="+json.dumps(entry['scopeNote'],ensure_ascii=False)+";window.PCRelease.history=["+j+",...window.PCRelease.history];\n</script><script>\n/* PC LAB content pack 0.1.0."
if marker not in s:raise SystemExit('release marker missing')
s=s.replace(marker,inject,1)
p.write_text(s)
